Repository Kalkuli/2018.2-Kalkuli_Front-End, pull requests merged in 2018-11, with the labels that each got.

#31 Solve #163 inserirCadastroDeEmpresas
  package-lock.json
  src/assets/img/error.svg
  src/assets/sass/base/_typography.scss
  src/components/HomePage/HomePage.js
  src/components/Receipt/ReceiptAdder/ReceiptAdder.js
  src/components/Register/Form.js
  src/components/Register/Form.scss
  src/components/Reports/Reports.js
  src/components/UI/Button/SignUp/SignUp.js
  src/components/UI/Confirmation/Confirmation.js
  src/components/UI/Confirmation/Confirmation.scss
  src/components/UI/Input/Input.js
  src/components/UI/Input/InputFild.js
  src/components/UI/Navbar/HomeNavBar/HomeNavBar.js
  src/components/UI/Navbar/HomeNavBar/HomeNavBar.scss
  src/components/__tests__/Register.test.js
  src/helpers/registerInputs.js
Labels: User Story

#38 Solve #192CorrigirFluxosDaAplicação
  src/App.js
  src/components/Dashboard/Dashboard.js
  src/components/HomePage/HomePage.js
  src/components/Receipt/ReceiptAdder/ReceiptAdder.js
  src/components/Receipt/ReceiptCompare/ReceiptCompare.js
  src/components/Receipt/ReceiptList/List.js
  src/components/Receipt/ReceiptList/ReceiptList.js
  src/components/Register/Form.js
  src/components/Reports/Reports.js
  src/components/__tests__/ReceiptList.test.js
  src/services/deleteReceipt.js
  src/services/getAllReceipts.js
  src/services/getAllTags.js
  src/services/logUserIn.js
  src/services/newTag.js
  src/store/reducers/reducer.js
Labels: UI & UX

#48 Solve #204 gerar relatorio por categoria
  src/components/Dashboard/Dashboard.js
  src/components/Dashboard/Dashboard.scss
  src/components/Reports/Reports.js
  src/components/Reports/Reports.scss
  src/components/UI/Button/ReportsButton/ReportsButton.js
  src/components/UI/Button/ReportsButton/ReportsButton.scss
  src/components/UI/DropDown/DropDown.js
  src/components/UI/DropDown/DropDown.scss
  src/components/UI/Report/Report.scss
  src/components/UI/TagItem/TagItem.scss
  src/components/__tests__/components/DropDown.test.js
  src/components/__tests__/components/Reports.test.js
  src/components/__tests__/components/ReportsButton.test.js
  src/components/__tests__/helpers/filterReceipts.test.js
  src/helpers/filterReceipts.js
  src/services/__mocks__/getAllReports.js
  src/services/getAllReports.js
Labels: UI & UX, User Story

#50 Solve #221 AjustarResponsividadeDaAplicacao
  package.json
  src/components/Dashboard/Dashboard.js
  src/components/Dashboard/Dashboard.scss
  src/components/HomePage/Header.js
  src/components/HomePage/HomePage.js
  src/components/HomePage/footer.scss
  src/components/HomePage/header.scss
  src/components/Receipt/ReceiptAdder/ReceiptAdder.js
  src/components/Receipt/ReceiptAdder/ReceiptAdder.scss
  src/components/Receipt/ReceiptCompare/ReceiptCompare.js
  src/components/Receipt/ReceiptCompare/ReceiptCompare.scss
  src/components/Receipt/ReceiptList/List.js
  src/components/Receipt/ReceiptList/ReceiptList.scss
  src/components/Receipt/ReceiptView/ReceiptView.js
  src/components/Receipt/ReceiptView/ReceiptView.scss
  src/components/Reports/Reports.js
  src/components/UI/BarChart/BarChart.js
  src/components/UI/Button/BaseButton/BaseButton.scss
  src/components/UI/Button/MenuButton/MenuButton.js
  src/components/UI/Colors/Colors.js
  src/components/UI/Receipt/Receipt.js
  src/components/UI/TagItem/SavedTagItem/SavedTagItem.js
  src/components/UI/TagItem/SavedTagItem/SavedTagItem.scss
  src/components/__tests__/components/HomePage.test.js
  src/components/__tests__/components/MenuButton.test.js
  src/components/__tests__/components/ReceiptAdder.test.js
  src/components/__tests__/components/ReceiptCompare.test.js
Labels: UI & UX

#53 Hotfix 404 Route
  src/components/Register/Form.js
  src/components/__tests__/components/Register.test.js
  static.json
Labels: hotfix

#52 Hotfix #235 Processo de cadastro com validação incorreta
  src/components/Register/Form.js
  src/components/__tests__/components/Register.test.js
Labels: hotfix
